placeholders:
    view_content_data_additional_information:
        items:
            demacmedia_livechat_chats_view: ~
items:
    demacmedia_livechat_chats_view:
        template: DemacMediaOroLivechatIntegrationBundle:LivechatInc:livechat-specific-user.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %orocrm_account.account.entity.class%)
