parameters:
    demacmedia.livechat.provider.livechat_channel_type.class:   DemacMedia\Bundle\OroLivechatIntegrationBundle\Provider\LivechatChannelType
    demacmedia.livechat.provider.rest_transport.class:          DemacMedia\Bundle\OroLivechatIntegrationBundle\Provider\Transport\RestTransport
    demacmedia.livechat.form.type.rest_transport.type.class:    DemacMedia\Bundle\OroLivechatIntegrationBundle\Form\Type\RestTransportType
    demacmedia.livechat.provider.livechat_chat.connector.class: DemacMedia\Bundle\OroLivechatIntegrationBundle\Provider\Connector\ChatConnector
    demacmedia.livechat.client_factory.class:                   DemacMedia\Bundle\OroLivechatIntegrationBundle\Model\LivechatClientFactory


services:
    demacmedia.livechat.client_factory:
        class: %demacmedia.livechat.client_factory.class%

    demacmedia.livechat.provider.livechat_channel_type:
        class: %demacmedia.livechat.provider.livechat_channel_type.class%
        tags:
            - { name: oro_integration.channel, type: live_chat }

    demacmedia.livechat.provider.rest_transport:
        class: %demacmedia.livechat.provider.rest_transport.class%
        arguments:
            - @demacmedia.livechat.client_factory
        tags:
            - { name: oro_integration.transport, type: rest, channel_type: live_chat }

    demacmedia.livechat.form.type.rest_transport.type:
        class: %demacmedia.livechat.form.type.rest_transport.type.class%
        arguments:
            - @demacmedia.livechat.provider.rest_transport
        tags:
            - { name: form.type, alias: demacmedia_livechat_form_rest_transport_type }

    demacmedia.livechat.provider.livechat_chat.connector.class:
        class: %demacmedia.livechat.provider.livechat_chat.connector.class%
        arguments:
            - @oro_importexport.context_registry
            - @oro_integration.logger.strategy
            - @oro_integration.provider.connector_context_mediator
            - @doctrine
        tags:
            - { name: oro_integration.connector, type: chat, channel_type: live_chat }
