# security:
#    firewalls:
#        livechat_integration:
#            pattern:                        ^/livechat
#            security:                       false
#            anonymous: ~

#    access_control:
#      - { path: ^/livechat, roles: IS_AUTHENTICATED_ANONYMOUSLY }

parameters:
    demacmedia.livechat.user: 'example@example.org'
    demacmedia.livechat.key:  'a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0a0'
